debug: true
devBaseBranch: main
productionBranch: main
nickname: saybot
gitlabHost: https://git.saybot.net
publishList:
  - name: publish-to-dev
    source: current
    target: dev
  - name: publish-to-prod
    source: beta
    target: master
