debug: true
devBaseBranch: dev
productionBranch: main
nickname: saybot
publishList:
  - name: publish-to-dev
    source: current
    target: dev
  - name: publish-to-prod
    source: beta
    target: master
